### ISSUE TITLE
Dot Files not being copied

### ISSUE THREAD

**Issue by Pedroglp** [garygrossgarten/github-action-scp#10]
Well, I do not know if it was expected to scp copy dot files but it isn't.

Since I have many of my server configurations in those files my build was not successful.

**Comment by hapo-tuannd** [comment]
Yes, i have same problem, scp can't copy  dot file like: `.env`, dot folder like `.hidden` folder. 
I just try, but not working
```
with:
    local: build/.
    remote: /build
```

**Comment by BernhardBehrendt** [comment]
Reason is a npm dependency [node-ssh](https://github.com/steelbrain/node-ssh)
More exactly [this](https://github.com/steelbrain/node-ssh/blob/b910aff8d382868784362851d12b029bcc4e37d9/src/index.ts#L61) default validation.

But for today I'm done ;-)

**Comment by DavideViolante** [comment]
This seems to work instead https://github.com/garygrossgarten/github-action-scp

**Comment by garygrossgarten** [comment]
The latest version (0.7.0) should now support dotfiles.
