### ISSUE TITLE
Delete content of remote directory before copy

### ISSUE THREAD

**Issue by ThomasRutzer** [garygrossgarten/github-action-scp#11]
Hey, would it make sense to add a feature to clean the remote directory before copy?
Could be an optional parameter.

Could be a simple `rm -rf [remote-folder-name]` and `node-ssh` already provides [`execCommand`](https://github.com/steelbrain/node-ssh#api) for that.

I've tried it and started PR #12 . Maybe you have a look and test it.

**Comment by garygrossgarten** [comment]
@ThomasRutzer  This could ne helpful, thanks for your PR. I'll take a look soon.

**Comment by ThomasRutzer** [comment]
@garygrossgarten Do you have a test environment for your action?
