### ISSUE TITLE
Trying to copy from root but it's empty

### ISSUE THREAD

**Issue by ctocph** [garygrossgarten/github-action-scp#15]
Hi,
I'm trying to copy using this:

`name: scp copy folder to remote via SSH

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
          local: /
          remote: something.com/public_html/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
      env:
          CI: true`

But nothing gets copied. Tried local: /., . even certain folders but nothing gets copied at all.
If I use the mkdir-example, THAT works.

How do I copy my entire code to the server on push?
Spent a few hours googling and trying.
Maybe it's folder rights, but as I can create on the server without any problems with the copy code, I doubt it.
Again - I just want to copy my entire code to the server, meaning, I want to deploy when I push. 

Any ideas out there?

thanks

**Comment by garygrossgarten** [comment]
Sorry for not coming back earlier. For anyone wanting to copy their github repo to a remote you need to check out your repo first. Add this step at the beginning of your job:

  ```
- name: checkout
   uses: actions/checkout@v2
```

Otherwise your workflow workspace will be empty
