### ISSUE TITLE
 multiple file transfers be added in future releases

### ISSUE THREAD

**Issue by TC-zerol** [garygrossgarten/github-action-scp#4]
Dear Author:
Your action is very easy to use
Can multiple file transfers be added in future releases
Similar to:
local: ./test1, ./test2
remote: ./test1, ./test2

**Comment by sideokyou** [comment]
I think it would be nice to add like this

Keep the current setups, but allow the host to have multiple hosts

```
local: test
host: ['server1', 'server2']
username: xxx
password: xxx
remote: /var/www/xxxx

```
