### ISSUE TITLE
Remove Node js 12,its deprecated.

### ISSUE THREAD

**Issue by Hopertz** [garygrossgarten/github-action-scp#40]
I get this warning while using the action "Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: garygrossgarten/github-action-scp"

**Comment by scottnunemacher** [comment]
Getting the same.

![Screen Shot 2022-11-07 at 3 44 14 PM](https://user-images.githubusercontent.com/29971822/200431363-399f54fe-4118-44f9-8876-ef6aa40228a7.png)
