### ISSUE TITLE
Update to nodejs v20

### ISSUE THREAD

**Issue by a-schild** [garygrossgarten/github-action-scp#46]
Using this action reults in this warning in my actions

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: garygrossgarten/github-action-scp@release.`

**Comment by undg** [comment]
I've created a PR that addresses this issue. 
In the meantime, feel free to use the fork from the PR: https://github.com/garygrossgarten/github-action-scp/pull/49


`undg/github-action-scp@master`

**Comment by garygrossgarten** [comment]
Thank you, the changes have been pushed in the latest release 0.9.0. Thank you for your patience.

**Comment by a-schild** [comment]
@garygrossgarten Thanks
